### ISSUE TITLE
sdist on PyPI broken with new setuptools

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.i18nmessageid#22]
Similar to https://github.com/zopefoundation/zope.interface/issues/184. This breaks, for example, PyPy3 builds: https://travis-ci.org/zopefoundation/zope.container/jobs/660521875#L268
```
Collecting zope.i18nmessageid
  Downloading zope.i18nmessageid-5.0.0.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/travis/virtualenv/pypy3.6-7.1.1/bin/pypy3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rd8qof6w/zope.i18nmessageid/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rd8qof6w/zope.i18nmessageid/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-rd8qof6w/zope.i18nmessageid/pip-egg-info
         cwd: /tmp/pip-install-rd8qof6w/zope.i18nmessageid/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rd8qof6w/zope.i18nmessageid/setup.py", line 25, in <module>
        from setuptools import setup, find_packages, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I think we just need to publish a new release, code in master has removed this.

**Comment by mgedmin** [comment]
For the record, the PR that removed the use of the deprecated Feature feature was #19.

I'll add a changelog note and push a release.

**Comment by mgedmin** [comment]
5.0.1 release pushed, we're waiting for CI builders now.

**Comment by mgedmin** [comment]
manylinux and Windows wheels done, MacOS is slow as usual.

Next: zope.hookable?  (Still uses Feature in setup.py in git master, a release won't cut it, ~~someone-not-me will have to prepare a PR~~ oh look [a PR](https://github.com/zopefoundation/zope.hookable/pull/15)!)

**Comment by jamadden** [comment]
Thanks!
